[package]
name = "test_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logs = { path = "../utils/logs" }
smol = { workspace = true }
regex = "1.10.3"